version: '3.8'

services:
  bot:
    container_name: feedback_bot
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    env_file:
      - ../.env
    volumes:
      # Mount source code for live reload
      - ../backend/src:/app/src
      # Mount Google Cloud credentials as read-only
      - ../google_creds.json:/app/google_creds.json:ro
    depends_on:
      - redis

  redis:
    container_name: feedback_redis
    image: redis:5-alpine
    ports:
      - "6379:6379"
