version: '3.8'

services:
  bot:
    container_name: feedback_bot
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../backend/src:/app/src
    depends_on:
      - redis

  redis:
    container_name: feedback_redis
    image: redis:5-alpine
    ports:
      - "6379:6379"
